# Generated by Django 5.2.7 on 2025-10-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grado',
            field=models.CharField(blank=True, help_text='Grado que enseña el docente (si aplica).', max_length=10, null=True, verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nivel',
            field=models.CharField(blank=True, choices=[('INICIAL', 'Inicial'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], help_text='Nivel educativo donde enseña el docente.', max_length=20, null=True, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='seccion',
            field=models.CharField(blank=True, help_text='Sección a cargo del docente.', max_length=10, null=True, verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto.', max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='turno',
            field=models.CharField(blank=True, choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde')], help_text='Turno en el que trabaja el docente.', max_length=20, null=True, verbose_name='Turno'),
        ),
    ]
