# Generated by Django 5.2.7 on 2025-10-20 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_grado_alter_user_nivel_alter_user_seccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
    ]
