# Generated by Django 5.2.7 on 2025-10-21 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificativo del bien, por ejemplo: “Mesa de madera” o “Proyector Epson X200”.', max_length=200, verbose_name='Nombre del bien')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales sobre el bien, su estado físico o características.', verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('MOVIL', 'Bien Móvil'), ('INMOVIL', 'Bien Inmóvil')], help_text='Indica si el bien es móvil (puede trasladarse) o inmóvil (instalado permanentemente).', max_length=20, verbose_name='Tipo')),
                ('codigo_inventario', models.CharField(help_text='Código único de inventario para identificar el bien o grupo de bienes.', max_length=50, unique=True, verbose_name='Código de inventario')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Número total de unidades de este bien (por ejemplo: 5 mesas o 10 sillas).', verbose_name='Cantidad')),
                ('ubicacion', models.CharField(blank=True, help_text='Lugar físico donde se encuentra el bien o grupo de bienes.', max_length=200, null=True, verbose_name='Ubicación')),
                ('fecha_adquisicion', models.DateField(help_text='Fecha en la que el bien fue adquirido.', verbose_name='Fecha de adquisición')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('DANADO', 'Dañado'), ('BAJA', 'Dado de baja')], default='DISPONIBLE', help_text='Situación actual del bien: disponible, en uso, dañado o dado de baja.', max_length=20, verbose_name='Estado')),
                ('imagen', models.ImageField(blank=True, help_text='Fotografía del bien (opcional).', null=True, upload_to='bienes/', verbose_name='Imagen')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que el bien fue registrado en el sistema.', verbose_name='Fecha de registro')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de la última modificación del registro.', verbose_name='Última actualización')),
                ('registrado_por', models.ForeignKey(help_text='Usuario del sistema que registró este bien.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('responsable_actual', models.ForeignKey(blank=True, help_text='Usuario que actualmente tiene el bien bajo su responsabilidad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable actual')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Bienes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asignacion', models.CharField(choices=[('PRESTAMO', 'Préstamo temporal'), ('ASIGNACION', 'Asignación permanente')], help_text='Indica si se trata de un préstamo temporal o una asignación permanente.', max_length=20, verbose_name='Tipo de asignación')),
                ('cantidad_asignada', models.PositiveIntegerField(default=1, help_text='Número de unidades del bien que se asignan al usuario.', verbose_name='Cantidad asignada')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('DEVUELTO', 'Devuelto'), ('TRANSFERIDO', 'Transferido')], default='ACTIVA', help_text='Estado actual de la asignación: activa, devuelto o transferido.', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, help_text='Notas o comentarios adicionales sobre esta asignación.', verbose_name='Observaciones')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la asignación del bien.', verbose_name='Fecha de asignación')),
                ('fecha_devolucion_programada', models.DateField(blank=True, help_text='Fecha prevista para la devolución (solo para préstamos temporales).', null=True, verbose_name='Fecha de devolución programada')),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, help_text='Fecha y hora en que el bien fue efectivamente devuelto.', null=True, verbose_name='Fecha de devolución real')),
                ('asignado_por', models.ForeignKey(help_text='Usuario del sistema que realizó la asignación del bien.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('bien', models.ForeignKey(help_text='Bien que se asigna o presta al usuario.', on_delete=django.db.models.deletion.CASCADE, related_name='historial_asignaciones', to='assets.asset', verbose_name='Bien')),
                ('usuario', models.ForeignKey(help_text='Usuario que recibe el bien asignado o en préstamo.', on_delete=django.db.models.deletion.CASCADE, related_name='historial_bienes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignación de Bien',
                'verbose_name_plural': 'Asignaciones de Bienes',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
