# Generated by Django 5.2.7 on 2025-10-26 23:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='fecha_adquisicion',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha en la que el bien fue adquirido.', verbose_name='Fecha de adquisición'),
        ),
    ]
